// <auto-generated />
using System;
using BoilerPlateWithRepos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoilerPlateWithRepos.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231005015253_Populate.tb_game")]
    partial class Populatetb_game
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoilerPlateWithRepos.Api.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("game", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b60f059a-2cd8-48ee-b4c0-db3e577f081f"),
                            Description = "bla bla",
                            Name = "Elden Ring"
                        },
                        new
                        {
                            Id = new Guid("2cd305a3-55ec-484c-9df1-adc7bc7c417c"),
                            Description = "ble ble",
                            Name = "Crash Bandicoot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
